stages:
  prepare_data:
    cmd: python -m src.pipeline.prepare_data
    deps:
      - src/components/data_ingestion.py
      - src/components/data_transformation.py
      - src/pipeline/prepare_data.py
      - src/utils.py
      - src/logger.py
      - src/expection.py
      - data/dummy_bdd100k/bdd100k/labels/bdd100k_labels_images_val.json
    params:
      - params.yaml:
          - data.use_dummy
          - data.random_seed
          - data.kaggle_dataset
          - data.processed_vqa_path
    outs:
      - data/processed/bdd100k_risk_vqa.json

  train:
    cmd: python -m src.pipeline.training_pipeline
    deps:
      - src/pipeline/training_pipeline.py
      - src/training_args.py
      - src/model.py
      - src/components/dataloader.py
      - config/qlora_config.yaml
      - data/processed/bdd100k_risk_vqa.json
    params:
      - params.yaml:
          - data.processed_vqa_path
      - .env:
          - NUM_TRAIN_EPOCHS
          - LEARNING_RATE
          - PER_DEVICE_TRAIN_BATCH_SIZE
    outs:
      - artifacts/blip2-finetuned-vqa
